#!/usr/bin/env bash


shell_stuff_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

source $shell_stuff_dir/lib/validators

path=$(requireArgument "$1" 'need a path as argument') || exit 1


readarray -t extensions < <(ls $path | cut -s -d . -f 2-)
if [[ ${#extensions[@]} ==  0 ]]; then
	felttip green "No ordering needed"
	exit 0
fi

IFS=,
felttip green "found ${#extensions[@]} extensions: $(echo "${extensions[*]}" | tr '[:upper:]' '[:lower:]')"
unset IFS



for ext in ${extensions[@]}; do
	mkdir $ext 2>/dev/null
	mv *.$ext $ext
done

felttip green "Content of $1 has been ordered in folders by extension"
