#!/usr/bin/env bash
shell_stuff_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

source $shell_stuff_dir/lib/validators

file=$(requireArgument "$1" 'need a file') || exit 1
input=$(requireArgument "$2" 'need txt to prepend') || exit 1

sed -i -e "1i$input\\" "$file"
